name: Test

on: [push, pull_request]

jobs:
  request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Request Postman Echo GET
        uses: ./
        with:
          url: 'https://postman-echo.com/get'
          method: 'GET'
      
      - name: Request Postman Echo POST
        uses: ./
        with:
          url: 'https://postman-echo.com/post'
          method: 'POST'
          data: '{ "key": "value" }'
      
      - name: Request Postman Echo POST with Unescaped Newline
        uses: ./
        with:
          url: 'https://postman-echo.com/post'
          method: 'POST'
          escapeData: 'true'
          data: >-
            {
              "key":"multi line\ntest
              text"
            }
      
      - name: Request Postman Echo BasicAuth
        uses: ./
        with:
          url: 'https://postman-echo.com/basic-auth'
          method: 'GET'
          username: 'postman'
          password: 'password'
      
      - name: Request Postman Echo with 404 Response and ignore failure code
        uses: ./
        with:
          url: 'https://postman-echo.com/status/404'
          method: 'GET'
          ignoreStatusCodes: '404'
      
      - name: Create Test File
        run: |
          echo "test" > testfile.txt

      - name: Request Postman Echo POST Multipart
        uses: ./
        with:
          url: 'https://postman-echo.com/post'
          method: 'POST'
          data: '{ "key": "value" }'
          files: '{ "file": "${{ github.workspace }}/testfile.txt" }'

      - name: Request Postman Echo POST Multipart without data
        uses: ./
        with:
          url: 'https://postman-echo.com/post'
          method: 'POST'
          files: '{ "file": "${{ github.workspace }}/testfile.txt" }'

      - name: Request Postman Echo POST single file
        uses: ./
        with:
          url: 'https://postman-echo.com/post'
          method: 'POST'
          file: "${{ github.workspace }}/testfile.txt"
