name: Test

on: [push, pull_request]

jobs:
  request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Request Postment Echo GET
        uses: ./
        with:
          url: 'https://postman-echo.com/get'
          method: 'GET'
      
      - name: Request Postment Echo POST
        uses: ./
        with:
          url: 'https://postman-echo.com/post'
          method: 'POST'
          data: '{ "key": "value" }'
      
      - name: Request Postment Echo BasicAuth
        uses: ./
        with:
          url: 'https://postman-echo.com/basic-auth'
          method: 'POST'
          username: 'postman'
          password: 'password'
